smallest positive integer program
joynewton1996/Daily_Program pull request #17
Opened 2021-05-11 15:38 UTC by joynewton1996

2021-05-11 16:55 UTC, roy-einstein requested changes
Try to USE ``` Sets ``` , intersection, difference, which can be solved very easily with these

2021-05-11 16:55 UTC, roy-einstein commented on hacker_Rank/May8_Answer.py
> +    return sequence
Why do you need this ?

2021-05-11 16:55 UTC, roy-einstein commented on hacker_Rank/May8_Answer.py
> +        for value in sequence:
sequence can be = range(1,Max_value+1) ???

2021-05-11 16:55 UTC, roy-einstein commented on hacker_Rank/May8_Answer.py
> +        return [1]
A= [1,3,6,4,5]
ouput == 2,
loop thru A, if you find smallest missing element break the loop and send ``` 1 ```
A=[1,2,3,4]
output is -1,
if series and given A is same, then return -1

2021-05-11 19:49 UTC, joynewton1996 commented on hacker_Rank/May8_Answer.py
> +        for value in sequence:
yes. got the point

2021-05-12 04:19 UTC, roy-einstein requested changes
need some more work

2021-05-12 04:19 UTC, roy-einstein commented on hacker_Rank/May8_Answer.py
> +        Max_value = obj.max_value(a)
Why variable name ``` Max_value ``` capital in it

2021-05-12 04:19 UTC, roy-einstein commented on hacker_Rank/May8_Answer.py
> +        return difference[0]
``` return difference[0] ``` how do you [0] element is always a smaller

2021-05-12 04:19 UTC, roy-einstein commented on hacker_Rank/May8_Answer.py
> +        print(a)
why do need to convert into set...?

2021-05-12 05:18 UTC, roy-einstein requested changes
needs work

2021-05-12 07:27 UTC, roy-einstein approved these changes
Keep good work

2021-05-12 07:28 UTC, merged