May19
joynewton1996/Daily_Program pull request #31
Opened 2021-05-22 08:26 UTC by joynewton1996

2021-05-22 15:42 UTC, roy-einstein requested changes
need some more improvement

2021-05-22 15:42 UTC, roy-einstein commented on hacker_Rank/May19_Answer.py
> +        list_j = [j for j in range((-a[j] + j), (a[j] + j + 1))]
can we write ``` set(range((j-a[j]),(j+a[j]+1))) ```

2021-05-22 15:42 UTC, roy-einstein commented on hacker_Rank/May19_Answer.py
> +            list_k = [k for k in range((-a[k] + k), (a[k] + k + 1))]
same like above

2021-05-22 15:42 UTC, roy-einstein commented on hacker_Rank/May19_Answer.py
> +            if set(list_j).intersection(list_k):
then we can use directly, ``` list_j.intersection(list_k) ```

2021-05-24 06:49 UTC, joynewton1996 commented on hacker_Rank/May19_Answer.py
> +            list_k = [k for k in range((-a[k] + k), (a[k] + k + 1))]
resolved

2021-05-24 06:49 UTC, joynewton1996 commented on hacker_Rank/May19_Answer.py
> +            if set(list_j).intersection(list_k):
cant use set directley . need a counter

2021-05-24 07:19 UTC, roy-einstein requested changes
Need some more work

2021-05-24 07:19 UTC, roy-einstein commented on hacker_Rank/May19_Answer.py
> +            if set(list_j).intersection(list_k):
``` list_j ```  and ``` list_k ``` are already set, 
why do you need type conversation ?

2021-05-24 07:19 UTC, roy-einstein commented on hacker_Rank/May19_Answer.py
> +        list_j = set(range((-a[j] + j), (a[j] + j + 1)))
``` list_j ``` name is incorrect, 
because ``` list_j ``` is type of ``` set ``` not ``` list ```, but name suggests it is ``` list ```

2021-05-24 07:56 UTC, roy-einstein approved these changes
keep the good work

2021-05-24 07:56 UTC, merged